#Temporary travis file. will set up properly when i can be fucked

language: node_js
node_js:
  - "lts/*"
cache: yarn
cache:
yarn: true
before_install:
  # empty
notifications:
  slack: feinwaru:6x5Uv4tO4l1GEKsNh8F02Y9R

install:
  - yarn
  - yarn lint
  - yarn test

script:
  #

after_success:
  #

after_failure:
#
